"""Auto-generated models for huggingface.

DO NOT EDIT — run `python scripts/generate_models.py` to regenerate.
"""

from __future__ import annotations

from dino_ai.model import (
    Model,
    ModelCapabilities,
    ModelLimits,
    ModelPricing,
    ModelThinkingLevel,
)


class Huggingface:
    """Models for huggingface."""

    MINIMAXAI__MINIMAX_M2_1 = Model(
        id="MiniMaxAI/MiniMax-M2.1",
        name="MiniMax-M2.1",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=1.2,
            cache_read=0,
            cache_write=0,
        ),
    )

    MINIMAXAI__MINIMAX_M2_5 = Model(
        id="MiniMaxAI/MiniMax-M2.5",
        name="MiniMax-M2.5",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=1.2,
            cache_read=0.03,
            cache_write=0,
        ),
    )

    MINIMAXAI__MINIMAX_M2_7 = Model(
        id="MiniMaxAI/MiniMax-M2.7",
        name="MiniMax-M2.7",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=1.2,
            cache_read=0.06,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_235B_A22B_THINKING_2507 = Model(
        id="Qwen/Qwen3-235B-A22B-Thinking-2507",
        name="Qwen3-235B-A22B-Thinking-2507",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=3,
            cache_read=0,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_CODER_480B_A35B_INSTRUCT = Model(
        id="Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name="Qwen3-Coder-480B-A35B-Instruct",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=66536,
        ),
        pricing=ModelPricing(
            input=2,
            output=2,
            cache_read=0,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_CODER_NEXT = Model(
        id="Qwen/Qwen3-Coder-Next",
        name="Qwen3-Coder-Next",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=65536,
        ),
        pricing=ModelPricing(
            input=0.2,
            output=1.5,
            cache_read=0,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_NEXT_80B_A3B_INSTRUCT = Model(
        id="Qwen/Qwen3-Next-80B-A3B-Instruct",
        name="Qwen3-Next-80B-A3B-Instruct",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=66536,
        ),
        pricing=ModelPricing(
            input=0.25,
            output=1,
            cache_read=0,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_NEXT_80B_A3B_THINKING = Model(
        id="Qwen/Qwen3-Next-80B-A3B-Thinking",
        name="Qwen3-Next-80B-A3B-Thinking",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=2,
            cache_read=0,
            cache_write=0,
        ),
    )

    QWEN__QWEN3_5_397B_A17B = Model(
        id="Qwen/Qwen3.5-397B-A17B",
        name="Qwen3.5-397B-A17B",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=32768,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=3.6,
            cache_read=0,
            cache_write=0,
        ),
    )

    XIAOMIMIMO__MIMO_V2_FLASH = Model(
        id="XiaomiMiMo/MiMo-V2-Flash",
        name="MiMo-V2-Flash",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=4096,
        ),
        pricing=ModelPricing(
            input=0.1,
            output=0.3,
            cache_read=0,
            cache_write=0,
        ),
    )

    DEEPSEEK_AI__DEEPSEEK_R1_0528 = Model(
        id="deepseek-ai/DeepSeek-R1-0528",
        name="DeepSeek-R1-0528",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=163840,
            max_output_tokens=163840,
        ),
        pricing=ModelPricing(
            input=3,
            output=5,
            cache_read=0,
            cache_write=0,
        ),
    )

    DEEPSEEK_AI__DEEPSEEK_V3_2 = Model(
        id="deepseek-ai/DeepSeek-V3.2",
        name="DeepSeek-V3.2",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=163840,
            max_output_tokens=65536,
        ),
        pricing=ModelPricing(
            input=0.28,
            output=0.4,
            cache_read=0,
            cache_write=0,
        ),
    )

    DEEPSEEK_AI__DEEPSEEK_V4_PRO = Model(
        id="deepseek-ai/DeepSeek-V4-Pro",
        name="DeepSeek V4 Pro",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=1048576,
            max_output_tokens=393216,
        ),
        pricing=ModelPricing(
            input=1.74,
            output=3.48,
            cache_read=0.145,
            cache_write=0,
        ),
    )

    MOONSHOTAI__KIMI_K2_INSTRUCT = Model(
        id="moonshotai/Kimi-K2-Instruct",
        name="Kimi-K2-Instruct",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=131072,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=1,
            output=3,
            cache_read=0,
            cache_write=0,
        ),
    )

    MOONSHOTAI__KIMI_K2_INSTRUCT_0905 = Model(
        id="moonshotai/Kimi-K2-Instruct-0905",
        name="Kimi-K2-Instruct-0905",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=1,
            output=3,
            cache_read=0,
            cache_write=0,
        ),
    )

    MOONSHOTAI__KIMI_K2_THINKING = Model(
        id="moonshotai/Kimi-K2-Thinking",
        name="Kimi-K2-Thinking",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=262144,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=2.5,
            cache_read=0.15,
            cache_write=0,
        ),
    )

    MOONSHOTAI__KIMI_K2_5 = Model(
        id="moonshotai/Kimi-K2.5",
        name="Kimi-K2.5",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=262144,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=3,
            cache_read=0.1,
            cache_write=0,
        ),
    )

    MOONSHOTAI__KIMI_K2_6 = Model(
        id="moonshotai/Kimi-K2.6",
        name="Kimi-K2.6",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=262144,
            max_output_tokens=262144,
        ),
        pricing=ModelPricing(
            input=0.95,
            output=4,
            cache_read=0.16,
            cache_write=0,
        ),
    )

    ZAI_ORG__GLM_4_7 = Model(
        id="zai-org/GLM-4.7",
        name="GLM-4.7",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=2.2,
            cache_read=0.11,
            cache_write=0,
        ),
    )

    ZAI_ORG__GLM_4_7_FLASH = Model(
        id="zai-org/GLM-4.7-Flash",
        name="GLM-4.7-Flash",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0,
            output=0,
            cache_read=0,
            cache_write=0,
        ),
    )

    ZAI_ORG__GLM_5 = Model(
        id="zai-org/GLM-5",
        name="GLM-5",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=202752,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=1,
            output=3.2,
            cache_read=0.2,
            cache_write=0,
        ),
    )

    ZAI_ORG__GLM_5_1 = Model(
        id="zai-org/GLM-5.1",
        name="GLM-5.1",
        api="openai-completions",
        provider="huggingface",
        base_url="https://router.huggingface.co/v1",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=202752,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=1,
            output=3.2,
            cache_read=0.2,
            cache_write=0,
        ),
    )
