"""Auto-generated models for openai.

DO NOT EDIT — run `python scripts/generate_models.py` to regenerate.
"""

from __future__ import annotations

from dino_ai.model import (
    Model,
    ModelCapabilities,
    ModelLimits,
    ModelPricing,
    ModelThinkingLevel,
)


class Openai:
    """Models for openai."""

    GPT_4 = Model(
        id="gpt-4",
        name="GPT-4",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=8192,
            max_output_tokens=8192,
        ),
        pricing=ModelPricing(
            input=30,
            output=60,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_4_TURBO = Model(
        id="gpt-4-turbo",
        name="GPT-4 Turbo",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=4096,
        ),
        pricing=ModelPricing(
            input=10,
            output=30,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_4_1 = Model(
        id="gpt-4.1",
        name="GPT-4.1",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=1047576,
            max_output_tokens=32768,
        ),
        pricing=ModelPricing(
            input=2,
            output=8,
            cache_read=0.5,
            cache_write=0,
        ),
    )

    GPT_4_1_MINI = Model(
        id="gpt-4.1-mini",
        name="GPT-4.1 mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=1047576,
            max_output_tokens=32768,
        ),
        pricing=ModelPricing(
            input=0.4,
            output=1.6,
            cache_read=0.1,
            cache_write=0,
        ),
    )

    GPT_4_1_NANO = Model(
        id="gpt-4.1-nano",
        name="GPT-4.1 nano",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=1047576,
            max_output_tokens=32768,
        ),
        pricing=ModelPricing(
            input=0.1,
            output=0.4,
            cache_read=0.03,
            cache_write=0,
        ),
    )

    GPT_4O = Model(
        id="gpt-4o",
        name="GPT-4o",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=2.5,
            output=10,
            cache_read=1.25,
            cache_write=0,
        ),
    )

    GPT_4O_2024_05_13 = Model(
        id="gpt-4o-2024-05-13",
        name="GPT-4o (2024-05-13)",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=4096,
        ),
        pricing=ModelPricing(
            input=5,
            output=15,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_4O_2024_08_06 = Model(
        id="gpt-4o-2024-08-06",
        name="GPT-4o (2024-08-06)",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=2.5,
            output=10,
            cache_read=1.25,
            cache_write=0,
        ),
    )

    GPT_4O_2024_11_20 = Model(
        id="gpt-4o-2024-11-20",
        name="GPT-4o (2024-11-20)",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=2.5,
            output=10,
            cache_read=1.25,
            cache_write=0,
        ),
    )

    GPT_4O_MINI = Model(
        id="gpt-4o-mini",
        name="GPT-4o mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=0.15,
            output=0.6,
            cache_read=0.08,
            cache_write=0,
        ),
    )

    GPT_5 = Model(
        id="gpt-5",
        name="GPT-5",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.125,
            cache_write=0,
        ),
    )

    GPT_5_CODEX = Model(
        id="gpt-5-codex",
        name="GPT-5-Codex",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.125,
            cache_write=0,
        ),
    )

    GPT_5_MINI = Model(
        id="gpt-5-mini",
        name="GPT-5 Mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0.25,
            output=2,
            cache_read=0.025,
            cache_write=0,
        ),
    )

    GPT_5_NANO = Model(
        id="gpt-5-nano",
        name="GPT-5 Nano",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0.05,
            output=0.4,
            cache_read=0.005,
            cache_write=0,
        ),
    )

    GPT_5_PRO = Model(
        id="gpt-5-pro",
        name="GPT-5 Pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=272000,
        ),
        pricing=ModelPricing(
            input=15,
            output=120,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_5_1 = Model(
        id="gpt-5.1",
        name="GPT-5.1",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.13,
            cache_write=0,
        ),
    )

    GPT_5_1_CHAT_LATEST = Model(
        id="gpt-5.1-chat-latest",
        name="GPT-5.1 Chat",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.125,
            cache_write=0,
        ),
    )

    GPT_5_1_CODEX = Model(
        id="gpt-5.1-codex",
        name="GPT-5.1 Codex",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.125,
            cache_write=0,
        ),
    )

    GPT_5_1_CODEX_MAX = Model(
        id="gpt-5.1-codex-max",
        name="GPT-5.1 Codex Max",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.25,
            output=10,
            cache_read=0.125,
            cache_write=0,
        ),
    )

    GPT_5_1_CODEX_MINI = Model(
        id="gpt-5.1-codex-mini",
        name="GPT-5.1 Codex mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0.25,
            output=2,
            cache_read=0.025,
            cache_write=0,
        ),
    )

    GPT_5_2 = Model(
        id="gpt-5.2",
        name="GPT-5.2",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_2_CHAT_LATEST = Model(
        id="gpt-5.2-chat-latest",
        name="GPT-5.2 Chat",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_2_CODEX = Model(
        id="gpt-5.2-codex",
        name="GPT-5.2 Codex",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_2_PRO = Model(
        id="gpt-5.2-pro",
        name="GPT-5.2 Pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=21,
            output=168,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_5_3_CHAT_LATEST = Model(
        id="gpt-5.3-chat-latest",
        name="GPT-5.3 Chat (latest)",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=False,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_3_CODEX = Model(
        id="gpt-5.3-codex",
        name="GPT-5.3 Codex",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_3_CODEX_SPARK = Model(
        id="gpt-5.3-codex-spark",
        name="GPT-5.3 Codex Spark",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=32000,
        ),
        pricing=ModelPricing(
            input=1.75,
            output=14,
            cache_read=0.175,
            cache_write=0,
        ),
    )

    GPT_5_4 = Model(
        id="gpt-5.4",
        name="GPT-5.4",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=1050000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=2.5,
            output=15,
            cache_read=0.25,
            cache_write=0,
        ),
    )

    GPT_5_4_MINI = Model(
        id="gpt-5.4-mini",
        name="GPT-5.4 mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0.75,
            output=4.5,
            cache_read=0.075,
            cache_write=0,
        ),
    )

    GPT_5_4_NANO = Model(
        id="gpt-5.4-nano",
        name="GPT-5.4 nano",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=400000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=0.2,
            output=1.25,
            cache_read=0.02,
            cache_write=0,
        ),
    )

    GPT_5_4_PRO = Model(
        id="gpt-5.4-pro",
        name="GPT-5.4 Pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=1050000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=30,
            output=180,
            cache_read=0,
            cache_write=0,
        ),
    )

    GPT_5_5 = Model(
        id="gpt-5.5",
        name="GPT-5.5",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=1050000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=5,
            output=30,
            cache_read=0.5,
            cache_write=0,
        ),
    )

    GPT_5_5_PRO = Model(
        id="gpt-5.5-pro",
        name="GPT-5.5 Pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=1050000,
            max_output_tokens=128000,
        ),
        pricing=ModelPricing(
            input=30,
            output=180,
            cache_read=0,
            cache_write=0,
        ),
    )

    O1 = Model(
        id="o1",
        name="o1",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=15,
            output=60,
            cache_read=7.5,
            cache_write=0,
        ),
    )

    O1_PRO = Model(
        id="o1-pro",
        name="o1-pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=150,
            output=600,
            cache_read=0,
            cache_write=0,
        ),
    )

    O3 = Model(
        id="o3",
        name="o3",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=2,
            output=8,
            cache_read=0.5,
            cache_write=0,
        ),
    )

    O3_DEEP_RESEARCH = Model(
        id="o3-deep-research",
        name="o3-deep-research",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=10,
            output=40,
            cache_read=2.5,
            cache_write=0,
        ),
    )

    O3_MINI = Model(
        id="o3-mini",
        name="o3-mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=1.1,
            output=4.4,
            cache_read=0.55,
            cache_write=0,
        ),
    )

    O3_PRO = Model(
        id="o3-pro",
        name="o3-pro",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=20,
            output=80,
            cache_read=0,
            cache_write=0,
        ),
    )

    O4_MINI = Model(
        id="o4-mini",
        name="o4-mini",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=1.1,
            output=4.4,
            cache_read=0.28,
            cache_write=0,
        ),
    )

    O4_MINI_DEEP_RESEARCH = Model(
        id="o4-mini-deep-research",
        name="o4-mini-deep-research",
        api="openai-completions",
        provider="openai",
        base_url="",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=100000,
        ),
        pricing=ModelPricing(
            input=2,
            output=8,
            cache_read=0.5,
            cache_write=0,
        ),
    )
