"""Auto-generated models for zhipu.

DO NOT EDIT — run `python scripts/generate_models.py` to regenerate.
"""

from __future__ import annotations

from dino_ai.model import (
    Model,
    ModelCapabilities,
    ModelLimits,
    ModelPricing,
    ModelThinkingLevel,
)


class Zhipu:
    """Models for zhipu."""

    GLM_4_5 = Model(
        id="glm-4.5",
        name="GLM-4.5",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=131072,
            max_output_tokens=98304,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=2.2,
            cache_read=0.11,
            cache_write=0,
        ),
    )

    GLM_4_5_AIR = Model(
        id="glm-4.5-air",
        name="GLM-4.5-Air",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=131072,
            max_output_tokens=98304,
        ),
        pricing=ModelPricing(
            input=0.2,
            output=1.1,
            cache_read=0.03,
            cache_write=0,
        ),
    )

    GLM_4_5_FLASH = Model(
        id="glm-4.5-flash",
        name="GLM-4.5-Flash",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=131072,
            max_output_tokens=98304,
        ),
        pricing=ModelPricing(
            input=0,
            output=0,
            cache_read=0,
            cache_write=0,
        ),
    )

    GLM_4_5V = Model(
        id="glm-4.5v",
        name="GLM-4.5V",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=64000,
            max_output_tokens=16384,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=1.8,
            cache_read=0,
            cache_write=0,
        ),
    )

    GLM_4_6 = Model(
        id="glm-4.6",
        name="GLM-4.6",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=2.2,
            cache_read=0.11,
            cache_write=0,
        ),
    )

    GLM_4_6V = Model(
        id="glm-4.6v",
        name="GLM-4.6V",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=128000,
            max_output_tokens=32768,
        ),
        pricing=ModelPricing(
            input=0.3,
            output=0.9,
            cache_read=0,
            cache_write=0,
        ),
    )

    GLM_4_7 = Model(
        id="glm-4.7",
        name="GLM-4.7",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.6,
            output=2.2,
            cache_read=0.11,
            cache_write=0,
        ),
    )

    GLM_4_7_FLASH = Model(
        id="glm-4.7-flash",
        name="GLM-4.7-Flash",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0,
            output=0,
            cache_read=0,
            cache_write=0,
        ),
    )

    GLM_4_7_FLASHX = Model(
        id="glm-4.7-flashx",
        name="GLM-4.7-FlashX",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=0.07,
            output=0.4,
            cache_read=0.01,
            cache_write=0,
        ),
    )

    GLM_5 = Model(
        id="glm-5",
        name="GLM-5",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=204800,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=1,
            output=3.2,
            cache_read=0.2,
            cache_write=0,
        ),
    )

    GLM_5_1 = Model(
        id="glm-5.1",
        name="GLM-5.1",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=False,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=6,
            output=24,
            cache_read=1.3,
            cache_write=0,
        ),
    )

    GLM_5V_TURBO = Model(
        id="glm-5v-turbo",
        name="GLM-5V-Turbo",
        api="openai-completions",
        provider="zhipu",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        capabilities=ModelCapabilities(
            reasoning=True,
            vision=True,
            tool_calling=True,
            streaming=True,
            supported_thinking_levels=(
                ModelThinkingLevel.OFF,
                ModelThinkingLevel.LOW,
                ModelThinkingLevel.MEDIUM,
                ModelThinkingLevel.HIGH,
            ),
        ),
        limits=ModelLimits(
            context_window=200000,
            max_output_tokens=131072,
        ),
        pricing=ModelPricing(
            input=5,
            output=22,
            cache_read=1.2,
            cache_write=0,
        ),
    )
